language: php
sudo: false

warnings_are_errors: false

php:
  - 7.3
install:
  - composer update --no-interaction
  - composer install  --no-interaction
  - composer require --dev phpunit/phpunit




script:
  - ./vendor/bin/phpunit --coverage-text --colors=never